version: 2
updates:
  - package-ecosystem: cargo
    directory: /src/rs/tessellation/
    schedule:
      interval: daily
    pull-request-branch-name:
      prefix: work/dependabot
      separator: '/'